Update schedule.yml

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -1,10 +1,3 @@
-name: Update Filtered EPG
-
-on:
-  schedule:
-    - cron: "0 12 * * *" # Runs daily at 12:00 PM UTC (01:00 AM NZT during daylight savings)
-  workflow_dispatch: # Allows manual triggering
-
 jobs:
   update-epg:
     runs-on: ubuntu-latest
@@ -17,12 +10,10 @@ jobs:
       run: |
         wget -O epg.xml.gz ${{ secrets.CRITICAL_LINK }}
 
-    - name: Verify File Download
+    - name: Verify XML Integrity
       run: |
-        echo "Listing current directory contents:"
-        ls -R
-        echo "Checking if epg.xml.gz exists:"
-        [ -f "epg.xml.gz" ] && echo "File exists!" || echo "File NOT found!"
+        gzip -d epg.xml.gz
+        xmllint epg.xml --noout || (echo "Invalid XML file detected!" && exit 1)
 
     - name: Move EPG File
       run: |
@@ -42,5 +33,5 @@ jobs:
         git config --global user.name "GitHub Actions Bot"
         git config --global user.email "actions@github.com"
         git add dialog.xml
-        git commit -m "Update filtered EPG"
+        git commit -m "Update filtered EPG" || echo "No changes to commit"
         git push
